import os
from datetime import datetime, date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def ensure_reports_dir() -> str:
    reports_dir = os.path.join("app", "static", "reports")
    os.makedirs(reports_dir, exist_ok=True)
    return reports_dir


def create_report_pdf(
    report_rows: list[dict],
    start_date: date,
    end_date: date,
    camera_name: str | None = None,
) -> str:
    reports_dir = ensure_reports_dir()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"doorvision_report_{timestamp}.pdf"
    file_path = os.path.join(reports_dir, filename)

    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30,
    )

    styles = getSampleStyleSheet()
    story = []

    title = Paragraph("DoorVision AI - Occupancy Report", styles["Title"])
    story.append(title)
    story.append(Spacer(1, 12))

    subtitle_text = f"Report Period: {start_date} to {end_date}"
    if camera_name:
        subtitle_text += f"<br/>Camera: {camera_name}"

    story.append(Paragraph(subtitle_text, styles["Normal"]))
    story.append(Spacer(1, 16))

    total_entry = sum(row["total_entry"] for row in report_rows)
    total_exit = sum(row["total_exit"] for row in report_rows)
    current_inside = sum(row["currently_inside"] for row in report_rows)
    peak_occupancy = max([row["peak_occupancy"] for row in report_rows], default=0)

    summary_data = [
        ["Total Entry", "Total Exit", "Currently Inside", "Peak Occupancy"],
        [total_entry, total_exit, current_inside, peak_occupancy],
    ]

    summary_table = Table(summary_data, colWidths=[120, 120, 120, 120])
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#F3F4F6")),
            ]
        )
    )

    story.append(summary_table)
    story.append(Spacer(1, 20))

    table_data = [
        [
            "Date",
            "Camera",
            "Entry",
            "Exit",
            "Inside",
            "Peak",
        ]
    ]

    for row in report_rows:
        table_data.append(
            [
                str(row["report_date"]),
                row.get("camera_name") or f"Camera {row['camera_id']}",
                row["total_entry"],
                row["total_exit"],
                row["currently_inside"],
                row["peak_occupancy"],
            ]
        )

    if len(table_data) == 1:
        table_data.append(["No data", "-", 0, 0, 0, 0])

    report_table = Table(
        table_data,
        colWidths=[80, 150, 60, 60, 70, 60],
        repeatRows=1,
    )

    report_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (2, 1), (-1, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")]),
            ]
        )
    )

    story.append(report_table)
    story.append(Spacer(1, 20))

    footer = Paragraph(
        "Generated by DoorVision AI - AI CCTV People Counting System",
        styles["Italic"],
    )
    story.append(footer)

    doc.build(story)

    return file_path.replace("\\", "/")